umatiGateway/Pages/Configuration.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using UmatiGateway.OPC;

namespace UmatiGateway.Pages
{
    public class ConfigurationModel : PageModel
    {
        private String SessionId = "";
        private ClientFactory ClientFactory;
        public Configuration configuration { get; set; } = new Configuration();
        public Configuration loadedConfiguration { get; set; } = new Configuration();

        public ConfigurationModel(ClientFactory ClientFactory)
        {
            this.ClientFactory = ClientFactory;
        }
        public void OnGet()
        {
            UmatiGatewayApp client = this.getClient();
            this.configuration = client.configuration;
            this.loadedConfiguration = client.loadedConfiguration;
        }
        public IActionResult OnPostDownload()
        {
            // Create file content (this could be any dynamically generated content)
            var fileContent = "Hello, this is a sample text file generated in Razor Pages!";

            // Convert the content to a byte array
            var byteArray = Encoding.UTF8.GetBytes(fileContent);

            // Return the file with content, MIME type, and suggested file name
            return File(byteArray, "text/plain", "sample.txt");
        }
        public IActionResult OnPostLoad(string FileContent)
        {
            UmatiGatewayApp client = this.getClient();
            ConfigurationReader configReader = new ConfigurationReader();
            this.loadedConfiguration = configReader.ReadConfiguration(FileContent);
            client.loadedConfiguration = this.loadedConfiguration;
            return RedirectToPage();
        }
        private UmatiGatewayApp getClient()
        {
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId == null)
            {
                this.SessionId = Guid.NewGuid().ToString();
                HttpContext.Session.SetString("SessionId", this.SessionId);
            }
            else
            {
                this.SessionId = mySessionId;
            }
            UmatiGatewayApp client = ClientFactory.getClient(this.SessionId);
            return client;
        }
    }
}

umatiGateway/Pages/CustomEncodings.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using UmatiGateway;
using UmatiGateway.OPC;
using UmatiGateway.OPC.CustomEncoding;

namespace umatiGateway.Pages
{
    public class CustomEncodingsModel : PageModel
    {
        private String SessionId = "";
        private ClientFactory ClientFactory;
        public CustomEncodingManager CustomEncodingsManager { get; set; } = new CustomEncodingManager();
        public CustomEncodingsModel(ClientFactory clientFactory)
        {
            this.ClientFactory = clientFactory;
        }
        public void OnGet()
        {
            UmatiGatewayApp client = this.getClient();
            this.CustomEncodingsManager = client.MqttProvider.customEncodingManager;
        }
        public IActionResult OnPostSave(bool? GMSResultDataTypeEncoding, bool? ProcessingCategoryDataTypeEncoding)
        {
            UmatiGatewayApp client = this.getClient();
            Configuration config = client.configuration;
            CustomEncodingManager customEncodingManager = client.MqttProvider.customEncodingManager;
            ManagedCustomEncoding? gms = customEncodingManager.GetManagedCustomEncodingByName("GMSResultDataTypeEncoding");
            ManagedCustomEncoding? pc = customEncodingManager.GetManagedCustomEncodingByName("ProcessingCategoryDataTypeEncoding");
            if (gms != null)
            {
                if (GMSResultDataTypeEncoding == null)
                {
                    gms.IsActive = false;
                }
                else
                {
                    gms.IsActive = true;
                }
            }
            if (pc != null)
            {
                if (ProcessingCategoryDataTypeEncoding == null)
                {
                    pc.IsActive = false;
                }
                else
                {
                    pc.IsActive = true;
                }
            }
            customEncodingManager.SaveConfiguration(config.configFilePath);
            return RedirectToPage();
        }
        private UmatiGatewayApp getClient()
        {
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId == null)
            {
                this.SessionId = Guid.NewGuid().ToString();
                HttpContext.Session.SetString("SessionId", this.SessionId);
            }
            else
            {
                this.SessionId = mySessionId;
            }
            UmatiGatewayApp client = ClientFactory.getClient(this.SessionId);
            return client;
        }
    }
}

umatiGateway/Pages/Error.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace UmatiGateway.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

umatiGateway/Pages/Index.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;
using System.Reflection;
using System.Resources;
using UmatiGateway.OPC;

namespace UmatiGateway.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private ClientFactory clientFactory;

        public IndexModel(ILogger<IndexModel> logger, ClientFactory ClientFactory)
        {
            _logger = logger;
            this.clientFactory = ClientFactory;
        }

        public void OnGet()
        {
            UmatiGatewayApp client = this.getClient(clientFactory);
            //client.StartUp();
        }
        private UmatiGatewayApp getClient(ClientFactory clientFactory)
        {
            string SessionId = "";
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId == null)
            {
                SessionId = Guid.NewGuid().ToString();
                HttpContext.Session.SetString("SessionId", SessionId);
            }
            else
            {
                SessionId = mySessionId;
            }
            UmatiGatewayApp client = clientFactory.getClient(SessionId);
            return client;
        }
    }
}

umatiGateway/Pages/OPCConnection.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;
using System.Collections.Concurrent;
using System.Reflection;
using System.Resources;
using UmatiGateway.OPC;

namespace UmatiGateway.Pages
{
    public class OPCConnectionModel : PageModel, UmatiGatewayAppListener
    {
        public string LabelConnectionUrl { get; } = "Connection URL:";
        public string LabelSessionId { get; } = "SessionId:";
        public string LabelOPCSessionName { get; } = "OPCSessionName:";
        public string LabelOPCSessionId { get; } = "OPCSessionId:";
        public string LabelConnectionStatus { get; } = "ConnectionStatus:";
        public string ConnectionUrl { get; private set; } = "";
        public ClientFactory ClientFactory;
        public string SessionId { get; private set; } = "";
        public string OPCSessionName { get; private set; } = "";
        public string OPCSessionId { get; private set; } = "";
        public string ConnectionStatus { get; private set; } = "Not Connected";

        private static readonly BlockingCollection<string> UpdateQueue = new BlockingCollection<string>();
        public OPCConnectionModel(ClientFactory ClientFactory)
        {
            this.ClientFactory = ClientFactory;
            ResourceManager rm = new ResourceManager("UmatiGateway.Pages.TestPage", Assembly.GetExecutingAssembly());
            string? Label_ConnectionUrl_Translated = rm.GetString("TestPage_Label_ConnectionUrl");
            if (Label_ConnectionUrl_Translated != null) { this.LabelConnectionUrl = Label_ConnectionUrl_Translated; }
        }

        public IActionResult OnPostConnect(String ConnectionUrl)
        {
            this.ConnectionUrl = ConnectionUrl;
            UmatiGatewayApp client = this.getClient();
            if (ConnectionUrl != null)
            {
                _ = client.ConnectAsync(this.ConnectionUrl).Result;
            }
            this.UpdateClientData();
            return new PageResult();
        }
        public IActionResult OnPostDisconnect()
        {
            UmatiGatewayApp client = this.getClient();
            client.Disconnect();
            this.UpdateClientData();
            return new PageResult();
        }
        public void OnGet()
        {
            this.UpdateClientData();
        }
        private UmatiGatewayApp getClient()
        {
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId == null)
            {
                this.SessionId = Guid.NewGuid().ToString();
                HttpContext.Session.SetString("SessionId", this.SessionId);
            }
            else
            {
                this.SessionId = mySessionId;
            }
            UmatiGatewayApp client = ClientFactory.getClient(this.SessionId);
            return client;
        }
        private void UpdateClientData()
        {
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId == null)
            {
                this.SessionId = string.Empty;
                this.OPCSessionId = string.Empty;
                this.ConnectionStatus = string.Empty;
                this.OPCSessionName = string.Empty;
            }
            else
            {
                UmatiGatewayApp client = ClientFactory.getClient(mySessionId);
                client.AddUmatiGatewayAppListener(this);
                this.SessionId = mySessionId;
                if (client.Session != null)
                {
                    this.OPCSessionId = client.Session.SessionId.ToString();
                    this.ConnectionStatus = client.Session.Connected.ToString();
                    this.OPCSessionName = client.Session.SessionName;

                }
                this.ConnectionUrl = client.getOpcConnectionUrl();
            }
        }
        public IActionResult OnGetStreamUpdates()
        {
            Response.ContentType = "text/event-stream";
            Response.Headers.Append("Cache-Control", "no-cache");
            Response.Headers.Append("Connection", "keep-alive");

            try
            {
                // Loop indefinitely, checking for updates
                foreach (var update in UpdateQueue.GetConsumingEnumerable())
                {
                    if (Response.HttpContext.RequestAborted.IsCancellationRequested)
                        break; // Exit if the client disconnects

                    var message = $"data: {update}\n\n";
                    Response.WriteAsync(message);
                    Response.Body.FlushAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in SSE connection: {ex.Message}");
            }

            return new EmptyResult();
        }

        public void blockingTransitionChanged(BlockingTransition blockingTransition)
        {
            var bt = new
            {
                transition = blockingTransition.Transition,
                message = blockingTransition.Message,
                detail = blockingTransition.Detail,
                isBlocking = blockingTransition.isBlocking
            };
            string jsonData = System.Text.Json.JsonSerializer.Serialize(bt);
            UpdateQueue.Add(jsonData); // Add update to the queue
        }
    }
}

umatiGateway/Pages/OPCSubscriptions.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;
using Opc.Ua;
using System.Reflection;
using System.Resources;
using UmatiGateway.OPC;

namespace UmatiGateway.Pages
{
    public class OPCSubscriptionsModel : PageModel
    {
        public ClientFactory ClientFactory;
        public Tree? BrowseTree { get; private set; }
        public OPCSubscriptionsModel(ClientFactory ClientFactory)
        {
            this.ClientFactory = ClientFactory;
        }
        public void OnGet()
        {
            UmatiGatewayApp? client = this.getClient();
            if (client != null)
            {
                client.BrowseRootNode();
                this.BrowseTree = client.BrowseTree;
            }
            else
            {
                //Put an Error here that the Client is not connected
            }

        }
        public IActionResult OnPostPublishNode(string uuid)
        {
            UmatiGatewayApp? client = this.getClient();
            if (client != null)
            {
                this.BrowseTree = client.BrowseTree;
                this.BrowseTree.SelectedTreeNode = uuid;
                TreeNode? selectedTreeNode = this.GetForUid(uuid);
                if (selectedTreeNode != null)
                {
                    client.publishNode(selectedTreeNode.NodeData.node.NodeId);
                }
            }
            return new PageResult();
        }
        public IActionResult OnPostBrowseSelectedTreeNode(string uuid)
        {
            UmatiGatewayApp? client = this.getClient();
            if (client != null)
            {
                this.BrowseTree = client.BrowseTree;
                this.BrowseTree.SelectedTreeNode = uuid;
                TreeNode? selectedTreeNode = this.GetForUid(uuid);
                if (selectedTreeNode != null && selectedTreeNode.IsExpanded == false)
                {
                    selectedTreeNode.IsExpanded = true;
                    client.BrowseSelectedTreeNode(selectedTreeNode);
                }
                else if (selectedTreeNode != null && selectedTreeNode.IsExpanded == true)
                {
                    selectedTreeNode.IsExpanded = false;
                    selectedTreeNode.children.Clear();
                }

            }
            else
            {
                //Put an Error here that the Client is not connected
            }
            return new PageResult();
        }
        private UmatiGatewayApp? getClient()
        {
            UmatiGatewayApp? client = null;
            string? mySessionId = HttpContext.Session.GetString("SessionId");
            if (mySessionId != null)
            {
                client = this.ClientFactory.getClient(mySessionId);
            }
            return client;
        }
        public TreeNode? GetForUid(string? uid)
        {
            if (uid == null) { return null; }
            UmatiGatewayApp? client = this.getClient();
            if (client != null)
            {
                this.BrowseTree = client.BrowseTree;
                if (this.BrowseTree.uids.TryGetValue(uid, out var node))
                {
                    //client.BrowseSelectedTreeNode(node);
                    return node;
                }
            }
            return null;
        }
    }
}

umatiGateway/Pages/Privacy.cshtml.cs
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved.
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace UmatiGateway.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

umatiGateway/Pages/Configuration.cshtml
@* SPDX-License-Identifier: Apache-2.0 *@
@* Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved. *@

@page
@model UmatiGateway.Pages.ConfigurationModel
@{
    ViewData["Title"] = "Configuration";
}
<h2>Configuration</h2>

<form id="upload-form" method="post">
    <div style="float:left; width:49%">
        <fieldset class="settings-fieldset">
        <legend class ="settings-legend">Active Configuration</legend>
        <!-- <div class="divider">Mqtt Configuration</div> -->
        <label for="OpcConnection" class="settings-label">OPC Server Endpoint</label>
        <input id="OpcConnection" class="settings-input" type="text" name="OpcConnectionUrl" value="@Model.configuration.opcServerEndpoint">
        <!-- <div class="divider">Mqtt Configuration</div> -->
        <label for="MqttConnection" class="settings-label">Mqtt Server Endpoint</label>
        <input id="MqttConnection" class="settings-input" type="text" name="MqttConnectionUrl" value="@Model.configuration.mqttServerEndpopint">
        <label for="MqttUser" class="settings-label">User</label>
        <input type="text" class="settings-input" id="MqttUser" name="MqttUser" value="@Model.configuration.mqttUser">
        <label for="Password" class="settings-label">Password</label>
        <input type="password" class="settings-input" id="Password" name="MqttPassword" value="@Model.configuration.mqttPassword">
        <label for="ClientId" class="settings-label">ClientId</label>
        <input type="text" class="settings-input" id="ClientId" name="MqttClientId" value="@Model.configuration.mqttClientId">
        <label for="Prefix" class="settings-label">Prefix</label>
        <input type="text"class="settings-input" id="Prefix" name="MqttPrefix" value="@Model.configuration.mqttPrefix">
        <!-- <div class="divider">Published Nodes</div> -->
        <table class="nodetable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Type</th>
                    <th>NamespaceUrl</th>
                    <th>Identifier</th>
                </tr>
            </thead>
            <tbody>
                @for (var i = 0; i < Model.configuration.publishedNodes.Count; i++)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@Model.configuration.publishedNodes[i].type</td>
                        <td>@Model.configuration.publishedNodes[i].namespaceUrl</td>
                        <td>@Model.configuration.publishedNodes[i].nodeId</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="settings-button-container">
            <button type="submit" asp-page-handler="Download" class="settings-button"> Download Active Configuration</button>
        </div>
        </fieldset>
    </div>
    <div style="float:right; width:49%">
        <fieldset class="settings-fieldset">
            <legend class="settings-legend" id="file-name-display">Configuration File</legend>
            <!-- <div class="divider">Mqtt Configuration</div> -->
            <label for="OpcConnection" class="settings-label">OPC Server Endpoint</label>
            <input id="OpcConnection" class="settings-input" type="text" name="OpcConnectionUrl" value="@Model.loadedConfiguration.opcServerEndpoint">
            <!-- <div class="divider">Mqtt Configuration</div> -->
            <label for="MqttConnection" class="settings-label">ConnectionUrl</label>
            <input id="MqttConnection" class="settings-input" type="text" name="MqttConnectionUrl" value="@Model.loadedConfiguration.mqttServerEndpopint">
            <label for="MqttUser" class="settings-label">User</label>
            <input type="text" class="settings-input" id="MqttUser" name="MqttUser" value="@Model.loadedConfiguration.mqttUser">
            <label for="Password" class="settings-label">Password</label>
            <input type="password" class="settings-input" id="Password" name="MqttPassword" value="@Model.loadedConfiguration.mqttPassword">
            <label for="ClientId" class="settings-label">ClientId</label>
            <input type="text" class="settings-input" id="ClientId" name="MqttClientId" value="@Model.loadedConfiguration.mqttClientId">
            <label for="Prefix" class="settings-label">Prefix</label>
            <input type="text" class="settings-input" id="Prefix" name="MqttPrefix" value="@Model.loadedConfiguration.mqttPrefix">
            <!-- <div class="divider">Published Nodes</div> -->
            <table class="nodetable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Type</th>
                        <th>NamespaceUrl</th>
                        <th>Identifier</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.configuration.publishedNodes.Count; i++)
                    {
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@Model.configuration.publishedNodes[i].type</td>
                            <td>@Model.configuration.publishedNodes[i].namespaceUrl</td>
                            <td>@Model.configuration.publishedNodes[i].nodeId</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="settings-button-container">
                <label for="file-upload" class="file-input-label-as-button">Load</label>
                <input type="file" id="file-upload" class="file-input">
                <!-- Verstecktes Feld zum Speichern des Datei-Inhalts -->
                <input type="hidden" id="file-content" name="FileContent" />
                <button asp-page-handler="Load" style="display:none" id="LoadButton">Apply</button>
                <button asp-page-handler="Apply" class="settings-button" style="margin-left:10px">Apply</button>
            </div>
        </fieldset>
    </div>
</form>
<script>
    const fileInput = document.getElementById('file-upload');
    const fileNameDisplay = document.getElementById('file-name-display');
    const fileContentInput = document.getElementById('file-content');
    const loadButton = document.getElementById('LoadButton')

    fileInput.addEventListener('change', function () {
        const file = fileInput.files[0];
        if (file) {
            const fileName = fileInput.files.length > 0 ? file.filename : "Keine Datei ausgewählt";
            fileNameDisplay.textContent = "Configuration File " + fileName;
            file.text().then(fileContent => {
                // Dateiinhalt in das versteckte Feld schreiben
                fileContentInput.value = fileContent;
                loadButton.click();
            }).catch(error => {
                console.error("Fehler beim Lesen der Datei:", error);
            })
        } 
    });
</script>

umatiGateway/Pages/CustomEncodings.cshtml
@* SPDX-License-Identifier: Apache-2.0 *@
@* Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved. *@

@page
@model umatiGateway.Pages.CustomEncodingsModel
@{
    ViewData["Title"] = "Custom Encodings";
}
<h1>Custom Encodings</h1>

<p>Enable or Disable Custom Encodings</p>

<form method="post">
    <div style="float:left; width:49%">
        <fieldset class="settings-fieldset">
            <legend class="settings-legend">Custom Encoding Configuration</legend>
            @{
                foreach (var customEncoding in Model.CustomEncodingsManager.managedCustomEncodings)
                {
                    <label for=@customEncoding.CustomEncoding.FullFieldName class="settings-label">@customEncoding.CustomEncoding.FullFieldName</label>
                    <div class="settings-on-off-label">
                        <span class="off">Off</span>
                        <label class="settings-switch">
                            <input id=@customEncoding.CustomEncoding.FullFieldName type="checkbox" name=@customEncoding.CustomEncoding.FullFieldName value="true" @(@customEncoding.IsActive ? "checked" : "")>
                            <span class="settings-slider"></span>
                        </label>
                        <span class="on">On</span>
                    </div>
                }
                <button type="submit" asp-page-handler="Save" class="settings-button">Speichern</button>
            }
        </fieldset>
    </div>
</form>

umatiGateway/Pages/Index.cshtml
@* SPDX-License-Identifier: Apache-2.0 *@
@* Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved. *@

@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

umatiGateway/Pages/OPCConnection.cshtml
@* SPDX-License-Identifier: Apache-2.0 *@
@* Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved. *@

@page
@model UmatiGateway.Pages.OPCConnectionModel
@{
    ViewData["Title"] = "OPC Connection";
}
<body>
<h1>OPC Connection</h1>

<p>Configure the connection to the OPC Server.</p>
<form method="post">
    <div style="float:left; width:49%">
    <fieldset class="settings-fieldset">
    <legend class="settings-legend">OPC Connection</legend>
    <label for="OPCConnection" class="settings-label">@Model.LabelConnectionUrl</label>
    <input id="OPCConnection" class="settings-input" type="text" name="ConnectionUrl" value="@Model.ConnectionUrl">
    <div class="settings-button-container">
        <button asp-page-handler="Connect" class="settings-button">Connect</button>
        <button asp-page-handler="Disconnect" class="settings-button" style="margin-left:10px">Disconnect</button>
    </div>
    <label for="SessionId" class="settings-label">@Model.LabelSessionId</label>
    <input id="SessionId" type="text" class="settings-input" value="@Model.SessionId" readonly />
    <label for="OPCSessionName" class="settings-label">@Model.LabelOPCSessionName</label>
    <input id="OPCSessionIdName" type="text" class="settings-input" value="@Model.OPCSessionName" readonly />
    <label for="OPCSessionId" class="settings-label">@Model.LabelOPCSessionId</label>
    <input id="OPCSessionId" type="text" class="settings-input" value="@Model.OPCSessionId" readonly />
    <label for="ConnectionStatus" class="settings-label">@Model.LabelConnectionStatus</label>
    <input id="ConnectionStatus" type="text" class="settings-input" value="@Model.ConnectionStatus" readonly />
    </fieldset>
    </div>
</form>

</body>

umatiGateway/Pages/umatiMqtt.cshtml
@* SPDX-License-Identifier: Apache-2.0 *@
@* Copyright (c) 2025 FVA GmbH - interop4x. All rights reserved. *@

@page
@model UmatiGateway.Pages.UmatiMqttModel
@{
    ViewData["Title"] = "UMATI Mqtt";
}
<h1>Umati Mqtt</h1>

<p>Configure your Umati Mqtt.</p>

<form method="post">
    <div style="float:left; width:49%">
        <fieldset class="settings-fieldset">
            <legend class="settings-legend">Mqtt Connection</legend>
            <label for="MqttUser" class="settings-label">User</label>
            <input type="text" class="settings-input" id="MqttUser" name="MqttUser" value="@Model.MqttUser">
            <label for="Password" class="settings-label">Password</label>
            <input type="password" class="settings-input" id="Password" name="MqttPassword" value="@Model.Password">
            <label for="ClientId" class="settings-label">ClientId</label>
            <input type="text" class="settings-input" id="ClientId" name="MqttClientId" value="@Model.ClientId">
            <label for="Prefix" class="settings-label">Prefix</label>
            <input type="text" class="settings-input" id="Prefix" name="MqttPrefix" value="@Model.Prefix">
            <label for="MqttConnection" class="settings-label">ConnectionUrl</label>
            <input id="MqttConnection" class="settings-input" type="text" name="ConnectionUrl" value="@Model.ConnectionUrl">
            <div class="settings-button-container">
                <button asp-page-handler="Connect" class="settings-button">Connect</button>
                <button asp-page-handler="Disconnect" class="settings-button" style="margin-left:10px">Disconnect</button>
            </div>
        </fieldset>
    </div>
    <div style="float:right; width:49%">
        <fieldset class="settings-fieldset">
            <legend class="settings-legend">Published Nodes</legend>
            <table class="nodetable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Type</th>
                        <th>NamespaceUrl</th>
                        <th>Identifier</th>
                        <th>BasisType</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.publishedNodes.Count; i++)
                    {
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@Model.publishedNodes[i].type</td>
                            <td>@Model.publishedNodes[i].namespaceUrl</td>
                            <td>@Model.publishedNodes[i].nodeId</td>
                            <td>@Model.publishedNodes[i].baseType</td>
                        </tr>
                    }
                </tbody>
            </table>
        </fieldset>
    </div>
</form>